# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: "ghcr.io"
  repository: "mirik12/kbot"
  tag: "v5.0.0-e1e880e"
  os: linux
  arch: amd64
  TELE_TOKEN: TELE_TOKEN

replicaCount: 1

service:
  port: 80

secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN

securityContext:
  privileged: true
